# Generated by Django 4.2.29 on 2026-06-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_storeitem_is_non_vrv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='is_vrv',
            field=models.BooleanField(default=False, help_text='Check if this item is VRV type.'),
        ),
    ]
