# Generated by Django 4.2.29 on 2026-06-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_storeitem_is_vrv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='is_non_vrv',
        ),
    ]
