# Generated by Django 4.2.29 on 2026-06-15 11:55

from django.db import migrations, models


def preserve_existing_item_types(apps, schema_editor):
    StoreItem = apps.get_model("store", "StoreItem")
    StoreItem.objects.filter(is_vrv=False).update(is_non_vrv=True)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_storeitem_is_non_vrv'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='is_non_vrv',
            field=models.BooleanField(default=False, help_text='Check if this item is Non-VRV type.'),
        ),
        migrations.RunPython(
            preserve_existing_item_types,
            migrations.RunPython.noop,
        ),
    ]
