# Generated by Django 4.2.29 on 2026-06-15 12:06

from django.db import migrations


def preserve_non_vrv_values(apps, schema_editor):
    StoreItem = apps.get_model("store", "StoreItem")
    for item in StoreItem.objects.filter(is_non_vrv=True).iterator():
        marker = "[NON_VRV]"
        remarks = (item.remarks or "").replace(marker, "").strip()[:239].rstrip()
        item.remarks = f"{remarks} {marker}".strip()
        item.save(update_fields=["remarks"])


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_storeitem_is_non_vrv'),
    ]

    operations = [
        migrations.RunPython(
            preserve_non_vrv_values,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='is_non_vrv',
        ),
    ]
